### ISSUE TITLE
RS485 information

### ISSUE THREAD

**Issue by Bwooce** [Xinyuan-LilyGO/T-Panel#3]
Small questions, after reading the RSM485 datasheet:
* S_GND is the isolated ground, so for RS485 GND wire?
* D_GND is for the outer cable shield? or for non-isolated RS485 GND?
* Is there a link to enable RS485 termination resistors? Or none on this board?

Nice board.

**Comment by Llgok** [comment]
> Small questions, after reading the RSM485 datasheet:
> 
> * S_GND is the isolated ground, so for RS485 GND wire?
> * D_GND is for the outer cable shield? or for non-isolated RS485 GND?
> * Is there a link to enable RS485 termination resistors? Or none on this board?
> 
> Nice board.

S_GND is the isolation voltage output negative pole of the module, usually used for connecting the ground wire of the signal line, mainly for transmitting data signals. 
D_GND is the ground wire of the digital circuit, used to connect the ground wire in the digital circuit.

The T-Panel_V1.0 version module RSM485MT5V has built-in terminal resistance, so there is no need to connect terminal resistance on the PCB and externally. 
The T-Panel_V1.2 version module does not have terminal resistance, so a 120-ohm terminal resistance is added to the PCB to ensure stable signal transmission.
