### ISSUE TITLE
I2C Arduino MPC9600

### ISSUE THREAD

**Issue by neilaw** [Xinyuan-LilyGO/T-Panel#4]
I am trying to get the T-Panel to connect to an Adruino MPC9600 thermocouple amplifier without any success.
I can connect to other I2C devices ok, just not the Adafruit MPC9600.
I tried connecting the T-panel to a 24vdc power supply to see if it was a power issue, but it didn't make any diffrence.
Using the IIC Scanner, it momentarily showed the address. so it seems to be working, but not sure why it doesn't see it all the time.
I tried chenging the address in the MPC9600, but it didn't make any diffrence.
Any Ideas?

**Comment by Llgok** [comment]
> Adruino MPC9600

Can you check if the power supply voltage for the MCP9600 device is normal?
