### ISSUE TITLE
lvgl support

### ISSUE THREAD

**Issue by isthaison** [Xinyuan-LilyGO/T-Panel#5]
Can this broad support lgvl ?

**Comment by Llgok** [comment]
> Can this broad support lgvl ?

The Lvgl examples have been added. 
Please go to "[./examples/Lvgl](./examples/Lvgl)" or "[./examples/Lvgl_benchmark](./examples/Lvgl_benchmark)" to view them.

**Comment by Llgok** [comment]
> Can this broad support lgvl ?

The Lvgl examples have been added. 
Please go to "[./examples/Lvgl](https://github.com/Xinyuan-LilyGO/T-Panel/tree/main/examples/Lvgl)" or "[./examples/Lvgl_benchmark](https://github.com/Xinyuan-LilyGO/T-Panel/tree/main/examples/Lvgl_benchmark)" to view them.
