### ISSUE TITLE
Please clarify details on CANFD

### ISSUE THREAD

**Issue by TobyLies** [Xinyuan-LilyGO/T-Panel#8]
### IDE and version or firmware

T-Panel_V1.3 CANFD

### Operating System

T-Panel_V1.3 CANFD

### Description

Can you give some clarification on the CANFD version of the board? Is it CAN (Controller Area Network) or is it CAN FD (Flexible Data)? If it's CANFD, I gather that TWAI isn't compatible with CANFD?

I don't see any other reference to CANFD in the github.

I want to use the T-Panel to read CAN messages in a car, and display info derived from it. Does the T-Panel both send and receive CAN messages? Or does it require an external board?

### Sketch

```cpp
n/a
```

### Debug Message

```plain
n/a
```

**Comment by Llgok** [comment]
@TobyLies 
The T-Panel CANFD version can automatically send and receive CAN messages.
Normal communication requires that your other device also supports the CAN protocol.
The following link provides an explanation of the CAN bus.
[CAN bus](https://en.wikipedia.org/wiki/CAN_bus)

You can refer to the following sample program to use CAN.
[CAN](https://github.com/Xinyuan-LilyGO/T-Panel/tree/arduino-esp32-libs_V2.0.14/examples/CAN)
[T-Panel_Test_V1_2](https://github.com/Xinyuan-LilyGO/T-Panel/tree/arduino-esp32-libs_V2.0.14/examples/T-Panel_Test_V1_2)

**Comment by aokhrimenko** [comment]
What CAN transceiver do you use on this board? I see nothing on schematics.

**Comment by viniciusro** [comment]
TD501MCANFD

**Comment by Llgok** [comment]
> What CAN transceiver do you use on this board? I see nothing on schematics.

@aokhrimenko 
@viniciusro 
The following is the data manual for the CAN module.
[TD501MCANFD_MORNSUN](https://github.com/Xinyuan-LilyGO/T-Panel/blob/arduino-esp32-libs_V2.0.14/information/TD501MCANFD_MORNSUN.pdf)

**Comment by Llgok** [comment]
Closed due to lack of response for a long time.
